GET  http://localhost:4000/subscribers/

###
GET http://localhost:4000/subscribers/60200352b7138913caf6db0a

###
POST  http://localhost:4000/subscribers/
Content-Type: application/json

{
    "name":"Amazing ppp",
    "subscribedToChannel":"Web dev simplified"
}

###
DELETE http://localhost:4000/subscribers/60200352b7138913caf6db0a


###
PATCH  http://localhost:4000/subscribers/60200352b7138913caf6db0a
Content-Type: application/json

{
    "name":"Amazing ppp",
    "subscribedToChannel":"Web dev simplified"
}